server:
  port: 8080

spring:
  application:
    name: research-graph

cognodb:
  uri: "bolt+s://db-f8989861.databases.cognodb.com"
  username: "cognodb"
  password: "******"
  database: "neo4j"

app:
  cors:
    allowed-origins: "http://localhost:5173"

logging:
  level:
    com.wexa.researchgraph: INFO